version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    volumes:
      - ./db/backup:/data/backup
      - ./db/data:/data/db
      - ./db/restore_backup.sh:/docker-entrypoint-initdb.d/restore_backup.sh
    ports:
      - 27017:27017
    restart: unless-stopped  